### ISSUE TITLE
The BootstrapDataServiceListener of Hilla starter uses window.Vaadin instead of window.Hilla to define SSO data 

### ISSUE THREAD

**Issue by taefi** [vaadin/sso-kit#112]
The `dev.hilla.sso.starter.BootstrapDataServiceListener` in `sso-kit-starter-hilla`, the script used to define the `SingleSignOnData` looks like the following:
```java
static final String SCRIPT_STRING = """
            window.Vaadin = window.Vaadin || {};
            window.Vaadin.SingleSignOnData = %s;
            """;
```
However, according to the [React](https://hilla.dev/docs/react/acceleration-kits/sso-kit/getting-started/#implement-authentication-state) and [Lit](https://hilla.dev/docs/lit/acceleration-kits/sso-kit/getting-started/#implement-authentication-state) docs, users are supposed to access it like this:

```typescript
(window as any).Hilla.SSO as SingleSignOnData;
```

So it seems that it should be defined as:

```java
static final String SCRIPT_STRING = """
            window.Hilla = window.Hilla || {};
            window.Hilla.SSO = %s;
            """;
```

Having the `SSO` data under `Hilla` object seems to be more convenient for Hilla users, However, if it is not possible to change the code, please consider updating the above mentioned docs.

**Comment by heruan** [comment]
Thanks for reporting this! It will be fixed once https://github.com/vaadin/docs/pull/2274 gets merged.
