### ISSUE TITLE
SSO-Kit 1.0.0 is not honouring JDK system properties for proxy settings

### ISSUE THREAD

**Issue by enver-haase** [vaadin/sso-kit#138]
I found this:
[https://github.com/spring-projects/spring-security/blame/main/oauth2/oauth2-client[…]rk/security/oauth2/client/registration/ClientRegistrations.java](https://github.com/spring-projects/spring-security/blame/main/oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java#L66)
Note the static {...} block starting line 62.
This is actually configuring the RestTemplate rest declared and instantiated in line 60.
What is interesting about it is that this is setting a SimpleClientHttpRequestFactory() -- that is, a "ClientHttpRequestFactory implementation that uses standard JDK facilities".  That means, this one is honouring the JDK system properties for Proxy Settings!!

Overriding spring-security-oauth2-client, spring-security-oauth2-jose, spring-security-config, spring-security-web, spring-security-core with version 5.8.9 introduced this feature.

Please can you release a 1.0.1 for Vaadin 23 (javax.servlet namespace) with updated Spring Security packages?

**Comment by tamasmak** [comment]
[1.0.1](https://github.com/vaadin/sso-kit/releases/tag/1.0.1) has been released.
