### ISSUE TITLE
Improve SSO Kit documentation about providers support

### ISSUE THREAD

**Issue by tamasmak** [vaadin/sso-kit#71]
In the SSO Kit documentation main [page](https://vaadin.com/docs/latest/tools/sso) the supported providers section could be improved with describing in more details what is needed for the SSO Kit to work with a provider considering the OpenID Connect specification. Also, mentioning that there are providers that are not fully supported yet.

**Comment by heruan** [comment]
- [x] Keycloak tutorial: https://github.com/vaadin/docs/pull/2112
- [ ] Okta tutorial: https://github.com/vaadin/docs/pull/2244

**Comment by heruan** [comment]
- [ ] Azure Active Directory: https://github.com/vaadin/docs/pull/2285
