### ISSUE TITLE
Create client-side library for SSO Kit for Hilla

### ISSUE THREAD

**Issue by tamasmak** [vaadin/sso-kit#72]
The SSO Kit for Hilla requires a lot of boilerplate TypeScript code on the client-side before we can make it work.
Currently, this code is documented in the Hilla documentation under the https://hilla.dev/docs/lit/acceleration-kits/sso-kit/getting-started and https://hilla.dev/docs/react/acceleration-kits/sso-kit/getting-started.

To resolve this, a client-side library should be created to encapsulate the necessary Typescript code needed to make the Kit work with Hilla.
After, the documentation should be also updated according to the changes.

**Comment by tamasmak** [comment]
Currently the sso-kit maven Java project consists of one parent module and five submodules. The project structure is that there is the parent POM and the child POMs for each submodule.

To be able to build the client-side library for SSO Kit for Hilla from this project we need to add Typescript code. This requires a new packaging solution for the Typescript code and a project structure change to store these files in a separate directory or package.

There is already a solution for a multi-module project like this with Java and Typescript code in the [Hilla project](https://github.com/vaadin/hilla). This project uses Maven packaging for Java modules and [Lerna’s](https://lerna.js.org/) packaging solution to create Typescript packages.
Based on this the sso-kit project’s new structure could be built up like this:

![project_structure](https://user-images.githubusercontent.com/11977763/223049798-fcb0e50f-4b6e-457c-a32a-ba998953615a.png)

The scripts for the Typescript package are in the `package.json` file in the root of the project.
A prototype of this solution can be found in the [client-side-library](https://github.com/vaadin/sso-kit/tree/feat/client-side-library) branch.

**Comment by heruan** [comment]
Do we really need to change the current Maven project structure, or this hierarchy might also work?

```
sso-kit/
├─ sso-kit-core/
│  └─ pom.xml
├─ sso-kit-starter/
│  └─ pom.xml
├─ sso-kit-starter-hilla/
│  └─ pom.xml
└─ sso-kit-client/
   ├─ sso-kit-client-lit/
   │  └─ package.json
   │  └─ tsconfig.json
   └─ sso-kit-client-react/
      ├─ package.json
      └─ tsconfig.json
```

**Comment by tamasmak** [comment]
Yes, the suggested hierarchy can also work and it is simpler. We will go forward with that.

**Comment by tamasmak** [comment]
I updated the [PR](https://github.com/vaadin/sso-kit/pull/75) for the SSO Kit Client Lit with the latest changes and finalized the implementation part. The testing is not ready yet. Added some instructions to the README about how to build and publish the package.

Now, using the client side library in a Hilla Lit application enables all the SSO Kit feartures and reduces the code needed before.

I also created a [PR](https://github.com/vaadin/docs/pull/2274) for the related SSO Kit for Hilla documentation update using the client library.

This is the current [documentation](https://hilla.dev/docs/lit/acceleration-kits/sso-kit/getting-started) and these screenshots show the updated sections with less code which will be in the new documentation:

![dependency](https://user-images.githubusercontent.com/11977763/224519468-36bba642-a5b4-4689-b77e-95310f9c053a.png)

![login_logout](https://user-images.githubusercontent.com/11977763/224519488-b27aefe5-93d5-42e2-9c77-b37c591c3be6.png)

![access_control](https://user-images.githubusercontent.com/11977763/224519492-24bf82f9-3574-429f-abda-6bd77badc637.png)

![user_information](https://user-images.githubusercontent.com/11977763/224519497-cfb0a09e-c665-46fb-a6fc-1d9f524be0c3.png)

![backchannel_logout](https://user-images.githubusercontent.com/11977763/224519500-e1da4711-8688-4c29-8521-344a7ac7967e.png)
